from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.about, name='about'),
    path('appointment/', views.MakeAppointmentView.as_view(), name='appointment'),
    path('contact/', views.contact, name='contact'),
    path('price/', views.price, name='price'),
    path('service/', views.service, name='service'),
    path('team/', views.TeamView.as_view(), name='team'),
    path('testimonial/', views.TestimonialView.as_view(), name='testimonial'),
    path('testimonial/add/', views.AddTestimonialView.as_view(), name='add-testimonial'),
    path('doctor/<int:pk>', views.DoctorDetailView.as_view(), name='doctor-detail'),
    path('doctor/<int:pk>/edit/', views.DoctorUpdateView.as_view(), name='doctor-update'),
    path('doctor/<int:pk>/deactivate/', views.DoctorDeactivateView.as_view(), name='doctor-deactivate'),
    path('my_appointment', views.MyAppointmentView.as_view(), name='my-appointment'),
    path('my-appointment/<int:pk>/edit/', views.AppointmentEditView.as_view(), name='my-appointment-edit'),
    path('send_message/', views.send_message, name='send-message'),
    path('find_doctor/', views.find_doctor, name='find-doctor'),
    path('api/doctors/', views.DoctorList.as_view()),
    path('api/doctors/<int:pk>/', views.DoctorDetail.as_view(), name='doctor-detail-api'),
    path('api/services/', views.ServiceList.as_view(), name='service-list'),
    path('api/services/<int:pk>/', views.ServiceDetail.as_view(), name='service-detail'),
    path('api/appointments/', views.AppointmentList.as_view(), name='appointment-list'),
    path('api/appointments/<int:pk>/', views.AppointmentDetail.as_view(), name='appointment-detail'),
    path('api/messages/', views.MessageList.as_view(), name='message-list'),
    path('api/messages/<int:pk>', views.MessageDetail.as_view(), name='message-detail'),
    path('appointments/', views.appointments, name='appointments'),
    path('doctor/appointments/', views.doctor_appointments, name='doctor-appointments'),
    path('appointment/<int:pk>/complete/', views.appointment_complete, name='appointment-complete'),
    path('appointment/update/<int:pk>/', views.AppointmentUpdateView.as_view(), name='appointment-update'),
    path('appointment/<int:pk>/cancel/', views.appointment_cancel, name='appointment-cancel'),
    path('appointment_history', views.AppointmentHistory, name='appointment-history'),
    path('appointment-history-client/<int:pk>/', views.AppointmentHistoryClient, name='appointment-history-client'),
    path('past/<int:pk>', views.show_past, name='show-past'),
    path('deleted/<int:pk>', views.show_cancelled, name='show-cancelled'),
    path('clients/', views.clients, name='clients'),
    path('services/', views.services, name='services'),
    path('service/update/<int:pk>/', views.ServiceUpdateView.as_view(), name='service-update'),
    path('service/<int:pk>/deactivate/', views.ServiceDeactivateView.as_view(), name='service-deactivate'),
    path('service/create/', views.ServiceCreateView.as_view(), name='service-create'),
    path('stoplist/<int:pk>', views.stoplist, name='stoplist'),
    path('services/<int:pk>', views.ServiceDetailPageView.as_view(), name='service-detail-page'),
    path('login/', views.MyLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reg/', views.RegView.as_view(), name='register'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.ProfileEditView.as_view(), name='profile-edit'),
    path('doctor/create/', views.DoctorCreateView.as_view(), name='doctor-create'),
    path('doctor/<int:pk>/update/', views.DoctorUpdateView.as_view(), name='doctor-update'),
    path('doctor/<int:pk>/deactivate/', views.DoctorDeactivateView.as_view(), name='doctor-deactivate'),
    path('doctors/', views.DoctorsManagerView.as_view(), name='doctors'),
    path('user/<int:pk>/delete/', views.UserDeleteView.as_view(), name='user-delete'),
    path('user/<int:pk>/edit/', views.UserEditView.as_view(), name='user-edit'),

    path('doctors_for_users/', views.DoctorsForUsersView.as_view(), name='doctors-for-users'),

    path('admin_dentcare/clients/', views.clients, name='admin_clients'),
    path('admin_dentcare/doctors/', views.DoctorsManagerView.as_view(), name='admin_doctors'),
    path('admin_dentcare/services/', views.services, name='admin_services'),
    path('admin_dentcare/all-users/', views.AllUsersView.as_view(), name='admin_all-users'),
]
